package de.tilliwilli.phantasien.model;

/**
 * BaseEntity is an interface implemented by all entity types. It defines means to get a unique
 * identifier for an entity and enforces some Active Record style pattern, allowing saving and
 * removing entity instances without needing to call a service or something.
 */
public interface BaseEntity {

	/**
	 * Returns the ID or some other identifier string that can be used to uniquely identify this
	 * entity along with its type and maybe some other information like its parent.<br>
	 * Remember that this method might return <tt>null</tt> if the entity is not yet persisted and
	 * the ID is auto-generated by the data store.
	 */
	public String getId();

	/**
	 * Persists this entity into the underlying data store.
	 */
	public void save();

	/**
	 * Removes this entity from the data store.
	 */
	public void remove();
}
